import type { Product, Customer } from './types';

export const products: Product[] = [
  {
    id: "PROD001",
    name: "Artisan Coffee Beans",
    sku: "ACB-250G",
    category: "Coffee",
    stock: 120,
    price: 15.99,
    status: "In Stock",
  },
  {
    id: "PROD002",
    name: "Classic Leather Wallet",
    sku: "CLW-BLK-01",
    category: "Accessories",
    stock: 75,
    price: 49.99,
    status: "In Stock",
  },
  {
    id: "PROD003",
    name: "Silk Scarf",
    sku: "SS-RED-LG",
    category: "Apparel",
    stock: 0,
    price: 29.99,
    status: "Out of Stock",
  },
  {
    id: "PROD004",
    name: "Canvas Tote Bag",
    sku: "CTB-NAT-MD",
    category: "Bags",
    stock: 25,
    price: 24.99,
    status: "Low Stock",
  },
  {
    id: "PROD005",
    name: "Designer Sunglasses",
    sku: "DS-TOR-55",
    category: "Accessories",
    stock: 40,
    price: 149.99,
    status: "In Stock",
  },
   {
    id: "PROD006",
    name: "Gourmet Chocolate Bar",
    sku: "GCB-DK-70",
    category: "Confectionery",
    stock: 200,
    price: 5.99,
    status: "In Stock",
  },
  {
    id: "PROD007",
    name: "Handcrafted Ceramic Mug",
    sku: "HCM-BLU-12",
    category: "Homeware",
    stock: 50,
    price: 19.99,
    status: "In Stock",
  },
  {
    id: "PROD008",
    name: "Organic Green Tea",
    sku: "OGT-CN-50",
    category: "Tea",
    stock: 80,
    price: 12.50,
    status: "In Stock",
  },
  {
    id: "PROD009",
    name: "Modern Desk Lamp",
    sku: "MDL-WHT-LED",
    category: "Lighting",
    stock: 15,
    price: 79.99,
    status: "Low Stock",
  },
  {
    id: "PROD010",
    name: "Wireless Bluetooth Speaker",
    sku: "WBS-GRY-V5",
    category: "Electronics",
    stock: 60,
    price: 89.99,
    status: "In Stock",
  },
];

export const customers: Customer[] = [
    {
        id: "CUST001",
        type: "individual",
        firstName: "Alice",
        lastName: "Johnson",
        companyName: null,
        email: "alice.j@email.com",
        phone: "555-0101",
        loyaltyPoints: 150,
    },
    {
        id: "CUST002",
        type: "individual",
        firstName: "Bob",
        lastName: "Williams",
        companyName: null,
        email: "bob.w@email.com",
        phone: "555-0102",
        loyaltyPoints: 75,
    },
    {
        id: "CUST003",
        type: "company",
        firstName: "Charlie",
        lastName: "Brown",
        companyName: "Brown Enterprises",
        email: "charlie@brownenterprises.com",
        phone: "555-0103",
    },
    {
        id: "CUST004",
        type: "individual",
        firstName: "Diana",
        lastName: "Miller",
        companyName: null,
        email: "diana.m@email.com",
        phone: "555-0104",
        loyaltyPoints: 230,
    },
    {
        id: "CUST005",
        type: "company",
        firstName: "Eva",
        lastName: "Green",
        companyName: "Green Goods Co.",
        email: "eva@greengoods.co",
        phone: "555-0105",
    },
];
